### pyファイルの実行

In [1]:
import numpy as np
import pandas as pd
import sys
from utils.split import scratch_train_test_split
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [2]:
# %run __.pyでjupyter上で実行
%run hello.py

Hello, World!


In [3]:
# argparserを利用
%run hello_argparse.py

0.1
RESULT : 102.4


In [4]:
# 引数を指定
%run hello_argparse.py --display --alpha 0.3 --text "Hello, argparse!" --num_iters 5

0.3
0.6
1.2
2.4
4.8
9.6
RESULT : 9.6


### 変更点
scratch train_test_split

random対応できました

さらにスッキリ書くことが出来ました

pyfile参照してください

In [5]:
# 上層にあるscratch_train_test_splitファイルの読み込み
sys.path.append('../ml-scratch/utils')
data = load_iris()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = scratch_train_test_split(X, y, train_size=0.8)

In [6]:
# scratchとscikitlearnを比較する
X_train, X_test, y_train, y_test = scratch_train_test_split(X, y, train_size = 0.8)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(len(X_train)/len(X))
print('-----------------------------')
print('-----------------------------')
# sklearn_train_test_split
sk_X_train, sk_X_test, sk_y_train, sk_y_test = train_test_split(X, y, test_size = 0.2)# train_sizeを揃える
print(sk_X_train.shape)
print(sk_X_test.shape)
print(sk_y_train.shape)
print(sk_y_test.shape)
print(len(sk_X_train)/len(X))

(120, 4)
(30, 4)
(120,)
(30,)
0.8
-----------------------------
-----------------------------
(120, 4)
(30, 4)
(120,)
(30,)
0.8


## 【問題2】 分類パイプラインの作成

行ったこと
Logistic_Regression, Support_Vector_Machine, Decision_Treeをそれぞれ異なる.py_fileとした(modelを切り替える)
file内部ではargparseを使って関数に渡す引数をまとめて格納する
dataをcsv化してpathを通すことにより3つのdataを切り替えることができる.
jupyter上で動作を確認

In [7]:
# iris DataFrame化
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target_names[iris.target]


In [8]:
#virgicolorとvirginica (setosaを除く)
df_vergicolor_and_virginica = df[df['target'] != 'setosa']


In [9]:
#iris dataをcsv_fileに書き出す(1度のみ実行)
 
#df_vergicolor_and_virginica.to_csv('df_vergicolor_and_virginica.csv')

In [10]:
#simple1 をfileに書き出す(1度のみ実行)

np.random.seed(seed=0)
n_samples = 500
f0= [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]

f0 = np.random.multivariate_normal(f0, cov, int(n_samples/2))
f1 = np.random.multivariate_normal(f1, cov, int(n_samples/2))
X = np.concatenate((f0, f1))
y = np.concatenate((np.ones((int(n_samples/2))), np.ones((int(n_samples/2))) *(-1))).astype(np.int)
random_index = np.random.permutation(np.arange(n_samples))
X = X[random_index]
y = y[random_index]

df_simple1 = pd.DataFrame(X, columns=['f0', 'f1'])
df_simple1['y'] = y

#df_simple1.to_csv('df_simple1.csv')

In [11]:
#simple_data2もcsvに(1度だけ実行)

X = np.array([[-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
       [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
       [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
       [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
       [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
       [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
       [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
       [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
       [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
       [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
       [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
       [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
       [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
       [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
       [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
       [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
       [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
       [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
       [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
       [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ]])
       
       
y = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
       
df = pd.DataFrame(X, columns=['X1', 'X2'])
df['target'] = y

#df.to_csv('df_simple2.csv')

### iris dataset

In [12]:
# iris_dataset Logistic_Regression
%run ../ml-scratch/utils/logistic_regression_clsifier.py --file_path  "C:/Users/umini/git-test/diveintocode-ml/ml-scratch/utils/df_vergicolor_and_virginica.csv" --penalty "l2" --test_size=0.3

1.0
['virginica' 'virginica' 'virginica' 'virginica' 'virginica' 'versicolor'
 'virginica' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'virginica' 'versicolor' 'versicolor' 'virginica' 'virginica' 'virginica'
 'versicolor' 'virginica' 'versicolor' 'versicolor' 'versicolor'
 'virginica' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'virginica' 'versicolor' 'versicolor'] ['virginica' 'virginica' 'virginica' 'virginica' 'virginica' 'versicolor'
 'virginica' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'virginica' 'versicolor' 'versicolor' 'virginica' 'virginica' 'virginica'
 'versicolor' 'virginica' 'versicolor' 'versicolor' 'versicolor'
 'virginica' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'virginica' 'versicolor' 'versicolor']


C:\Users\umini\Anaconda3\envs\pytorch\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [13]:
# iris SVM
%run ../ml-scratch/utils/support_vector_machine.py --file_path "C:/Users/umini/git-test/diveintocode-ml/ml-scratch/utils/df_vergicolor_and_virginica.csv" --C 2.0

1.0
['virginica' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'virginica' 'virginica' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'virginica' 'virginica'
 'versicolor' 'versicolor' 'virginica' 'versicolor' 'virginica'] ['virginica' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'virginica' 'virginica' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'virginica' 'virginica'
 'versicolor' 'versicolor' 'virginica' 'versicolor' 'virginica']


In [14]:
# iris decision_tree_classifier 
%run ../ml-scratch/utils/decision_tree.py --file_path "C:/Users/umini/git-test/diveintocode-ml/ml-scratch/utils/df_vergicolor_and_virginica.csv" --max_depth 3

1.0
['virginica' 'virginica' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'virginica' 'versicolor' 'versicolor'
 'versicolor' 'virginica' 'virginica' 'virginica' 'virginica' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'virginica'] ['virginica' 'virginica' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'virginica' 'versicolor' 'versicolor'
 'versicolor' 'virginica' 'virginica' 'virginica' 'virginica' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'virginica']


### simple1 dataset

In [15]:
# simple1 LogisticRegression
%run ../ml-scratch/utils/logistic_regression_clsifier.py --file_path  "C:/Users/umini/git-test/diveintocode-ml/ml-scratch/utils/df_simple1.csv" --penalty "l2" --test_size=0.3

1.0
[ 1 -1  1  1  1 -1  1  1  1  1  1 -1  1  1 -1 -1 -1  1  1 -1  1 -1 -1  1
 -1  1 -1 -1  1  1 -1  1 -1  1  1  1 -1  1  1 -1  1 -1  1  1  1 -1  1 -1
  1  1 -1 -1 -1  1 -1 -1 -1  1 -1  1  1 -1  1 -1 -1 -1  1  1 -1  1 -1 -1
 -1  1  1 -1 -1  1 -1 -1 -1  1  1  1 -1 -1 -1 -1  1  1  1 -1 -1  1  1  1
 -1  1  1 -1  1  1  1 -1 -1 -1 -1 -1 -1  1  1  1 -1 -1  1  1  1  1 -1 -1
  1  1 -1 -1  1  1  1 -1 -1  1 -1 -1  1  1  1 -1  1 -1 -1 -1  1 -1 -1 -1
  1 -1 -1 -1 -1 -1] [ 1 -1  1  1  1 -1  1  1  1  1  1 -1  1  1 -1 -1 -1  1  1 -1  1 -1 -1  1
 -1  1 -1 -1  1  1 -1  1 -1  1  1  1 -1  1  1 -1  1 -1  1  1  1 -1  1 -1
  1  1 -1 -1 -1  1 -1 -1 -1  1 -1  1  1 -1  1 -1 -1 -1  1  1 -1  1 -1 -1
 -1  1  1 -1 -1  1 -1 -1 -1  1  1  1 -1 -1 -1 -1  1  1  1 -1 -1  1  1  1
 -1  1  1 -1  1  1  1 -1 -1 -1 -1 -1 -1  1  1  1 -1 -1  1  1  1  1 -1 -1
  1  1 -1 -1  1  1  1 -1 -1  1 -1 -1  1  1  1 -1  1 -1 -1 -1  1 -1 -1 -1
  1 -1 -1 -1 -1 -1]


C:\Users\umini\Anaconda3\envs\pytorch\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [16]:
# simple1 SVM
%run ../ml-scratch/utils/support_vector_machine.py --file_path "C:/Users/umini/git-test/diveintocode-ml/ml-scratch/utils/df_simple1.csv" --C 2.0 --test_size  0.3

0.9133333333333333
[ 1 -1 -1  1  1 -1 -1 -1  1 -1 -1  1  1  1  1 -1  1  1  1 -1 -1 -1 -1 -1
 -1 -1 -1  1  1 -1 -1  1 -1 -1  1 -1  1  1  1 -1  1 -1 -1 -1  1  1  1  1
 -1 -1  1  1  1 -1  1  1 -1  1  1  1 -1 -1 -1 -1 -1  1  1  1 -1  1  1  1
 -1 -1  1  1 -1  1  1 -1 -1  1  1  1  1  1  1  1  1 -1 -1  1  1  1  1 -1
 -1 -1  1  1  1  1 -1  1  1  1  1 -1  1 -1  1  1 -1  1  1 -1  1 -1  1 -1
  1 -1 -1  1  1  1  1  1  1 -1  1 -1  1  1  1  1  1  1  1 -1 -1  1  1 -1
  1  1  1  1 -1  1] [ 1 -1 -1  1 -1 -1 -1 -1  1 -1 -1 -1 -1  1  1 -1  1  1  1 -1 -1 -1 -1 -1
 -1 -1 -1 -1  1 -1 -1  1 -1 -1  1 -1 -1  1 -1 -1  1 -1 -1 -1  1  1 -1  1
 -1 -1  1  1  1 -1  1  1 -1  1  1  1 -1 -1 -1 -1 -1  1  1  1 -1  1  1  1
 -1 -1  1  1 -1  1  1 -1 -1  1  1  1  1  1  1  1  1 -1 -1  1  1  1 -1 -1
 -1 -1  1 -1  1  1 -1  1  1  1 -1 -1  1 -1  1  1 -1 -1  1 -1 -1 -1  1 -1
  1 -1 -1  1 -1  1  1  1  1 -1  1 -1  1  1  1  1  1  1  1 -1 -1  1  1 -1
  1  1  1  1 -1  1]


In [17]:
# simple1 decision_tree_classifier 
%run ../ml-scratch/utils/decision_tree.py --file_path "C:/Users/umini/git-test/diveintocode-ml/ml-scratch/utils/df_simple1.csv" --max_depth 3

1.0
[-1 -1 -1 -1 -1  1 -1 -1 -1  1 -1  1  1 -1  1  1  1  1 -1 -1 -1 -1  1 -1
 -1  1 -1  1 -1  1 -1  1 -1  1  1  1 -1  1 -1 -1  1 -1  1 -1  1 -1  1 -1
 -1 -1 -1  1 -1  1  1 -1  1  1  1 -1 -1  1 -1 -1  1  1  1 -1 -1  1  1  1
  1  1 -1 -1 -1  1  1  1 -1  1 -1  1  1 -1  1 -1 -1 -1 -1 -1 -1 -1  1  1
  1 -1  1 -1] [-1 -1 -1 -1 -1  1 -1 -1 -1  1 -1  1  1 -1  1  1  1  1 -1 -1 -1 -1  1 -1
 -1  1 -1  1 -1  1 -1  1 -1  1  1  1 -1  1 -1 -1  1 -1  1 -1  1 -1  1 -1
 -1 -1 -1  1 -1  1  1 -1  1  1  1 -1 -1  1 -1 -1  1  1  1 -1 -1  1  1  1
  1  1 -1 -1 -1  1  1  1 -1  1 -1  1  1 -1  1 -1 -1 -1 -1 -1 -1 -1  1  1
  1 -1  1 -1]


### simple2 dataset

In [18]:
# simple2 LogisticRegression
%run ../ml-scratch/utils/logistic_regression_clsifier.py --file_path  "C:/Users/umini/git-test/diveintocode-ml/ml-scratch/utils/df_simple2.csv" --penalty "l2" --test_size=0.3

0.9166666666666666
[0 1 1 0 1 0 1 1 0 1 1 1] [0 1 0 0 1 0 1 1 0 1 1 1]


C:\Users\umini\Anaconda3\envs\pytorch\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [19]:
# simple2 SVM
%run ../ml-scratch/utils/support_vector_machine.py --file_path "C:/Users/umini/git-test/diveintocode-ml/ml-scratch/utils/df_simple2.csv" --C 2.0 --test_size  0.3

0.6666666666666666
[0 1 0 0 1 1 0 0 0 0 0 0] [0 1 1 1 1 1 0 0 1 0 0 1]


In [20]:
# simple2 decision_tree_classifier 
%run ../ml-scratch/utils/decision_tree.py --file_path "C:/Users/umini/git-test/diveintocode-ml/ml-scratch/utils/df_simple2.csv" --max_depth 3

1.0
[1 0 0 1 1 0 0 0] [1 0 0 1 1 0 0 0]


## 【問題3】 回帰パイプラインの作成

In [21]:
# session4のtrainfaile読み込み
df = pd.read_csv("C:/Users/umini/git-test/diveintocode-ml/week4/train.csv")
# GrLivArea', 'YearBuilt','SalePriceを抜き出す
df_grlivearea_yearbuilt = df[['GrLivArea', 'YearBuilt','SalePrice']]

In [22]:
#csv_fileに書き込む(1度だけ)

#df_grlivearea_yearbuilt.to_csv("df_grlivearea_yearbuilt.csv")

In [23]:
# House price LinearRegression
%run ../ml-scratch/utils/linear_regression.py --file_path  "C:/Users/umini/git-test/diveintocode-ml/ml-scratch/utils/df_grlivearea_yearbuilt.csv"

r2_score 0.6611679936695176
mse 1929337612.4286394
