# 課題1 内積を手計算しよう

In [1]:
import numpy as np
A = np.array([-1,2,3,4,-5,6,7,8,-9]).reshape(3,3)
A

array([[-1,  2,  3],
       [ 4, -5,  6],
       [ 7,  8, -9]])

In [2]:
B = np.array([0,2,1,0,2,-8,2,9,-1]).reshape(3,3)
B

array([[ 0,  2,  1],
       [ 0,  2, -8],
       [ 2,  9, -1]])

In [3]:
# use_adamal_sum
A = np.array([-1,2,3,4,-5,6,7,8,-9]).reshape(3,3)
B = np.array([0,2,1,0,2,-8,2,9,-1]).reshape(3,3)
A_column_size = A.shape[1]
B_line_size = B.shape[0]
A_line_size = A.shape[0]
# making empty matrix
AB = np.empty((B_line_size, A_column_size)) # Pass in tuple
print(AB)
for i in range(A_column_size):
    for j in range(B_line_size):
        # vector adamal and sum
        AB[i,j] = np.sum(A[i,:]*B[:,j])
        print(i,j)
print(AB)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 5.92878775e-322]
 [1.96353543e-077 0.00000000e+000 0.00000000e+000]]
0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [4]:
# 手計算
AB = np.array([6,29,-20,12,52,38,-18,-51,-48]).reshape(3,3)
AB

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 課題2, 3 for文で実装 
課題2と3を分割していません

In [5]:
# 1つ目の要素 A[0,0]B[0,0]+A[0,1]B[1,0]+A[0,2]B[2,0]
# Aの列とBの行が1ずつ増えるように
# for i in range(A_column_size):
# multiple += A[0,i]*B[i,0]
# 2つ目の要素 A[0,0]B[0,1]+A[0,1]B[1,1]+A[0,2]B[2,1]
# 3つ目の要素 A[0,0]B[0,2]+A[0,2]B[1,2]+A[0,2]B[2,2]
# Bの列が1ずつ増えるように
# for j in range(B_line_size):
# multiple = 0 和をリセット
# multiple += A[0,i]*B[i,j]
# 4つ目の要素 A[1,0]B[0,0]+A[1,1]B[1,0]+A[1,2]B[2,0]
# 7つ目の要素 A[2,0]B[0,0]+A[2,1]B[1,0]+A[2,2]B[2,0]
# Aの行が1ずつ増えるように
# for k in range(A_line_size):
# multiple += A[k,i]*B[i,j]
A_column_size = A.shape[1]
B_line_size = B.shape[0]
A_line_size = A.shape[0]
value_list = []

for k in range(A_line_size):
    for j in range(B_line_size):
        multiple = 0
        for i in range(A_column_size):
            multiple += A[k,i]*B[i,j]
            print('Aの行列{}{}'.format(k,i))
            print('Bの行列{}{}'.format(i,j))
            print(multiple)
            print('-------------')
        value_list.append(multiple)
            
print(value_list)
AB = np.array(value_list)
AB = AB.reshape(3,3)
print(AB)

Aの行列00
Bの行列00
0
-------------
Aの行列01
Bの行列10
0
-------------
Aの行列02
Bの行列20
6
-------------
Aの行列00
Bの行列01
-2
-------------
Aの行列01
Bの行列11
2
-------------
Aの行列02
Bの行列21
29
-------------
Aの行列00
Bの行列02
-1
-------------
Aの行列01
Bの行列12
-17
-------------
Aの行列02
Bの行列22
-20
-------------
Aの行列10
Bの行列00
0
-------------
Aの行列11
Bの行列10
0
-------------
Aの行列12
Bの行列20
12
-------------
Aの行列10
Bの行列01
8
-------------
Aの行列11
Bの行列11
-2
-------------
Aの行列12
Bの行列21
52
-------------
Aの行列10
Bの行列02
4
-------------
Aの行列11
Bの行列12
44
-------------
Aの行列12
Bの行列22
38
-------------
Aの行列20
Bの行列00
0
-------------
Aの行列21
Bの行列10
0
-------------
Aの行列22
Bの行列20
-18
-------------
Aの行列20
Bの行列01
14
-------------
Aの行列21
Bの行列11
30
-------------
Aの行列22
Bの行列21
-51
-------------
Aの行列20
Bの行列02
7
-------------
Aの行列21
Bの行列12
-57
-------------
Aの行列22
Bの行列22
-48
-------------
[6, 29, -20, 12, 52, 38, -18, -51, -48]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [6]:
# after_fixed 
A_column_size = A.shape[1]
B_line_size = B.shape[0]
A_line_size = A.shape[0]
# making empty matrix
AB = np.empty((B_line_size, A_column_size)) # Pass in tuple
for k in range(A_line_size):
    for j in range(B_line_size):
        multiple = 0
        for i in range(A_column_size):
            multiple += A[k,i]*B[i,j]
            print('Aの行列{}{}'.format(k,i))
            print('Bの行列{}{}'.format(i,j))
            print(multiple)
            print('-------------')
        AB[k,j] = multiple
print(AB)

Aの行列00
Bの行列00
0
-------------
Aの行列01
Bの行列10
0
-------------
Aの行列02
Bの行列20
6
-------------
Aの行列00
Bの行列01
-2
-------------
Aの行列01
Bの行列11
2
-------------
Aの行列02
Bの行列21
29
-------------
Aの行列00
Bの行列02
-1
-------------
Aの行列01
Bの行列12
-17
-------------
Aの行列02
Bの行列22
-20
-------------
Aの行列10
Bの行列00
0
-------------
Aの行列11
Bの行列10
0
-------------
Aの行列12
Bの行列20
12
-------------
Aの行列10
Bの行列01
8
-------------
Aの行列11
Bの行列11
-2
-------------
Aの行列12
Bの行列21
52
-------------
Aの行列10
Bの行列02
4
-------------
Aの行列11
Bの行列12
44
-------------
Aの行列12
Bの行列22
38
-------------
Aの行列20
Bの行列00
0
-------------
Aの行列21
Bの行列10
0
-------------
Aの行列22
Bの行列20
-18
-------------
Aの行列20
Bの行列01
14
-------------
Aの行列21
Bの行列11
30
-------------
Aの行列22
Bの行列21
-51
-------------
Aの行列20
Bの行列02
7
-------------
Aの行列21
Bの行列12
-57
-------------
Aの行列22
Bの行列22
-48
-------------
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [7]:
# use_adamal_sum
A_column_size = A.shape[1]
B_line_size = B.shape[0]
A_line_size = A.shape[0]
# making empty matrix
AB = np.empty((B_line_size, A_column_size)) # Pass in tuple
for i in range(A_column_size):
    for j in range(B_line_size):
        # vector adamal and sum
        AB[i,j] = np.sum(A[i,:]*B[:,j])
        print(i,j)
print(AB)

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


## 課題4 内積をnp.dotで計算しよう

In [8]:
np.dot(A, B)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 課題5 内積ができないときはどうするか


In [9]:
A = np.array([-1, 2, 3, 4, 5, 6])
A = A.reshape(2,3)
print(A)
print(A.T)
B = np.array([-9, 8, 7, 6, -5, 4])
B = B.reshape(2,3)
print(B)
print(B.T)
#AB = np.dot(A, B)
ATB = np.dot(A.T, B)
print(ATB)
ABT = np.dot(A, B.T)
print(ABT)

[[-1  2  3]
 [ 4  5  6]]
[[-1  4]
 [ 2  5]
 [ 3  6]]
[[-9  8  7]
 [ 6 -5  4]]
[[-9  6]
 [ 8 -5]
 [ 7  4]]
[[ 33 -28   9]
 [ 12  -9  34]
 [  9  -6  45]]
[[46 -4]
 [46 23]]
