## Task1

## Class enumeration
### pandas class
DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)

### matplotlib
figure
axes

### scikit-learn
DecisionTreeClassifier

RandomforestClassifier

LogisticRegression

LinearRegression

SVC

KMeans

NearestNeighbors

PCA


## Task 2 method and instance

## method

count(), isnull(), array(), arrange(), range(), mean(), read_csv(), std(), sqrt(), square(), list(), dict(),

## instance
.shape, .mean, .sum, .datetime, .time, .date

In [ ]:
z = (x - u) / s

In [26]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            学習データ
        """

        self.mean_ = X.mean()
        self.var_ = X.var()

        pass

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_) / np.sqrt(self.var_ + 1e-12)
        
        
        return X_scaled

In [27]:
import numpy as np
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 :", scratch_scaler.mean_)
print("分散 :", scratch_scaler.var_)
X_std = scratch_scaler.transform(X)
print(X_std)

# X_std.mena X_std_std
print(X_std.mean())
print(X_std.std())

平均 : 2.46
分散 : 3.1744
[[ 1.48174374  0.58371723 -0.59494256 -1.26846245]
 [ 1.36949043  0.30308395 -0.59494256 -1.26846245]
 [ 1.25723711  0.41533726 -0.65106922 -1.26846245]
 [ 1.20111046  0.3592106  -0.53881591 -1.26846245]
 [ 1.42561708  0.63984389 -0.59494256 -1.26846245]
 [ 1.65012371  0.80822386 -0.42656259 -1.15620913]
 [ 1.20111046  0.52759057 -0.59494256 -1.21233579]
 [ 1.42561708  0.52759057 -0.53881591 -1.26846245]
 [ 1.08885714  0.24695729 -0.59494256 -1.26846245]
 [ 1.36949043  0.3592106  -0.53881591 -1.3245891 ]]
8.881784197001253e-17
0.9999999999998425


In [28]:
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2

example = ExampleClass(5)
print("value :", example.value)
example.add(3)
print("value :", example.value)

初期値5が設定されました
value : 5
value : 8


In [60]:
value = 100

In [61]:
(type(value) != int) and (type(value) != float)

False

In [77]:
value = 0
if value == 0:
    print('0は入力できません')

0は入力できません


In [82]:
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        
        self.value = value
        if (type(self.value) != int) and (type(self.value) != float):
            self.value = 0
            print("初期値は数字にしてください.")
            
        else:
            print("初期値{}が設定されました".format(self.value))
        
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
        
        
    def subtraction(self, value3):
        """
        受け取った引数をself.valueからサブトラクションする
        """
        self.value -= value3
        
    def multiplication(self, value4):
        """
        受け取った引数をself.valueから掛け算する
        """
        self.value *= value4
        
    def division(self, value5):
        # 0のときは実行しない
        """
        受け取った引数をself.valueから割り算する
        """
        if value5 == 0:
            print('0は入力できません')
        else:
            self.value /= value5
        
    

example = ExampleClass(5)
print("value :", example.value)
example.add(3)
print("value :", example.value)
example.subtraction(4)
print("value :", example.value)
example.multiplication(3)
print("value :", example.value)
example.division(0)
print("value :", example.value)
example.division(40)
print("value :", example.value)

初期値5が設定されました
value : 5
value : 8
value : 4
value : 12
0は入力できません
value : 12
value : 0.3
